= Tennisverein
Julia König
1.0.0:
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

ifdef::backend-html5[]

== GraphQL

link:../backend/src/main/java/at/htl/tennis/boundary/TenniscourtResource.java[GraphQLQueriesImplementation]

link:../backend/graphql-queries/queries.graphql[GraphQLQueries]

link:../backend/src/main/java/at/htl/tennis/control/TenniscourtService.java[MethodImplementationForQueries]

.Warum benötige ich GraphQL?
GraphQL bietet die Möglichkeiten, genau das zu fragen, was man benötigt und nicht mehr.
Im Allgemeinen ist GraphQL eine Abfragesprache für APIs.

.Anwendung im Projekt
Ich habe GraphQL dazu verwendet um alle Tennisplätze, die in der Datenbank gespeichert sind auszugeben.

.Alternativen
* Swagger
* REST API

== Validation

link:../backend/src/main/java/at/htl/tennis/control/MemberService.java[ServiceValidation]

link:../backend/src/main/java/at/htl/tennis/boundary/MemberResource.java[ValidationMethods]

link:../backend/src/main/java/at/htl/tennis/entity/Member.java[ValidationAnnotation]

.Warum benötige ich Validierung?
Validierung bietet die Möglichkeit die Eingabe es Benutzers "einzuschränken".
Einschränken in dem Kontext, dass der Benutzer wie in meinem Beispiel einen Vornamen eingeben muss,
ansonsten wird eine Fehlermeldung ausgegeben.
Validierung kann frühzeitig prüfen, ob die geforderten Eingaben des Programmiers bzw.
Kunden vom Benutzer richtig durchgeführt wurden.

.Anwendung im Projekt
Ich habe die Validierung in der Klasse Member angewendet, da es dort nötig ist, dass von einem neuen
Mitglied zumindest der Vorname, Nachname und die E-Mail bekannt ist.

== Qute
