= Tennisverein
Julia König
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

ifdef::backend-html5[]

== GraphQL

link:../backend/src/main/java/at/htl/tennis/boundary/TenniscourtResource.java[GraphQL-queries implementation]

link:../backend/graphql-queries/queries.graphql[GraphQL-queries]

link:../backend/src/main/java/at/htl/tennis/control/TenniscourtService.java[Method implementation for queries]

.Wofür benötigt man GraphQL?
GraphQL bietet die Möglichkeiten, genau das zu fragen, was man benötigt und nicht mehr.
Im Allgemeinen ist GraphQL eine Abfragesprache für APIs.

.Anwendung im Projekt
Ich habe GraphQL dazu verwendet um alle Tennisplätze, die in der Datenbank gespeichert sind auszugeben.

.Alternativen
* Swagger
* REST API

== Validation

link:../backend/src/main/java/at/htl/tennis/control/MemberService.java[ServiceValidation]

link:../backend/src/main/java/at/htl/tennis/boundary/MemberResource.java[ValidationMethods]

link:../backend/src/main/java/at/htl/tennis/entity/Member.java[ValidationAnnotation]

link:../backend/http-requests/http-requests.http[try validation requests]

.Wofür benötigt man Validierung?
Validierung bietet die Möglichkeit die Eingabe es Benutzers "einzuschränken".
Einschränken in dem Kontext, dass der Benutzer wie in meinem Beispiel einen Vornamen eingeben muss,
ansonsten wird eine Fehlermeldung ausgegeben.
Validierung kann frühzeitig prüfen, ob die geforderten Eingaben des Programmiers bzw.
Kunden vom Benutzer richtig durchgeführt wurden.

.Anwendung im Projekt
Ich habe die Validierung in der Klasse Member angewendet, da es dort nötig ist, dass von einem neuen
Mitglied zumindest der Vorname, Nachname und die E-Mail bekannt ist.

== Qute Templating Engine

link:../backend/src/main/java/at/htl/tennis/boundary/MemberResource.java[getMemberMethod]

link:../backend/src/main/resources/templates/MemberResource/memberTemplate.html[Html-Page to print member]

link:../backend/http-requests/http-requests.http[Try last GET to test part of qute]

.Wofür benötigt man Qute?
Qute ist eine Templating-Engine, die speziell für die Anforderungen von Quarkus entwickelt wurde.
Die Verwendung von Reflektion wird minimiert, um die Größe nativer Bilder zu reduzieren.

.Anwendung im Projekt
Qute wurde bei der Member-Klasse angewendet. Mit einem GET-Request kann man einen Member durch Vorname, Nachname, Mail
und Telefonnummer "finden". Dieser wird dann mit dem memberTemplate.html grafisch in einem Browser abgebildet,
wenn man den GET-Request in einem Browser ausführt.

== GRPC