POST localhost:8080/member/service-method-validation
Content-Type: application/json

{
  "firstname": "Herbert",
  "lastname": "Wurm",
  "mail": ""
}

###

POST localhost:8080/member/manual-validation
Content-Type: application/json

{
  "firstname": "Herbert",
  "lastname": "Wurm",
  "mail": "herbert@wurm.mail"
}

###

POST localhost:8080/member/end-point-method-validation
Content-Type: application/json

{
  "firstname": "Herbert",
  "lastname": "Wurm",
  "mail": ""
}